fix: revert "build: upgrade to node 16"
This reverts commit fb13f0a94ef7b8022ab92d12763c7b28e5361665.

Breaks when releasing to heroku:

Error: Cannot find module '@heroku/buildpack-registry'